version: "3.7"

secrets:
  admiral_yml:
    file: ./secrets/admiral.yml

services:
  celery-shell:
    build:
      context: .
      dockerfile: Dockerfile-admiral
    image: admiral
    init: true
    command: --interactive # drop into an ipython celery shell
    environment:
      ADMIRAL_CONFIG_FILE: '/run/secrets/admiral_yml'
      ADMIRAL_CONFIG_SECTION: dev-mode
      ADMIRAL_WORKER_NAME: dev
    secrets:
      - source: admiral_yml
    volumes:
     - ./src/admiral:/usr/src/admiral/admiral
     - ./tests:/home/con/tests

  bash:
    build:
      context: .
      dockerfile: Dockerfile-admiral
    image: admiral
    init: true
    entrypoint: /bin/sh
    environment:
      ADMIRAL_CONFIG_FILE: '/run/secrets/admiral_yml'
      ADMIRAL_CONFIG_SECTION: dev-mode
      ADMIRAL_WORKER_NAME: dev
    secrets:
      - source: admiral_yml
    volumes:
     - ./src/admiral:/usr/src/admiral/admiral
     - ./tests:/home/con/tests

  test:
    build:
      context: .
      dockerfile: Dockerfile-admiral
    image: admiral
    init: true
    entrypoint: pytest
    environment:
      ADMIRAL_CONFIG_FILE: '/run/secrets/admiral_yml'
      ADMIRAL_CONFIG_SECTION: dev-mode
      ADMIRAL_WORKER_NAME: dev
    secrets:
      - source: admiral_yml
    volumes:
     - ./src/admiral:/usr/src/admiral/admiral
     - ./tests:/home/con/tests
